quiet: true
plugins:
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: false
  # must leave in xmlns so can be viewed in github
  - removeXMLNS: false
  - removeEditorsNSData: true
  - cleanupAttrs: true
  - inlineStyles: false
  - minifyStyles: false
  - convertStyleToAttrs: false
  - cleanupIDs: true
  - prefixIds: false
  - removeRasterImages: true
  - removeUselessDefs: true
  - cleanupNumericValues: false
  - cleanupListOfValues: false
  # will remove fill="#000000"
  - convertColors: false
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: false
  - removeViewBox: false
  - cleanupEnableBackground: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - convertShapeToPath: false
  - moveElemsAttrsToGroup: false
  - moveGroupAttrsToElems: false
  - collapseGroups: true
  - convertPathData: true
  - convertTransform: false
  - removeEmptyAttrs: true
  - removeEmptyContainers: true
  - mergePaths: false
  - removeUnusedNS: true
  - sortAttrs: true
  - removeTitle: false
  - removeDesc: true
  - removeDimensions: true
  - removeAttrs:
      attrs:
        - "xml:space"
        - "baseProfile"
  - removeElementsByAttr: false
  - addClassesToSVGElement: false
  - removeStyleElement: true
  - removeScriptElement: true
  - addAttributesToSVGElement:
      attributes:
        - xmlns: "http://www.w3.org/2000/svg"

js2svg:
  pretty: true
  indent: 4
